def create():

    print(" " * 35)
    print("|" + "=" * 63 + "|")
    print("|" + "-" * 63 + "|")
    print("|" + " " * 24 + "CRIAR REGISTROS:" + " " * 23 + "|")
    print("|" + "-" * 63 + "|")
    print("|" + " " * 63 + "|")
    print("|" + " " * 22 + "1. Adicionar dados." + " " * 22 + "|")
    print("|" + " " * 24 + "2. Listar dados." + " " * 23 + "|")
    print("|" + " " * 22 + "3. Atualizar dados." + " " * 22 + "|")
    print("|" + " " * 23 + "4. Deletar dados." + " " * 23 + "|")
    print("|" + " " * 63 + "|")
    print("|" + "-" * 63 + "|")
    print("|" + "=" * 63 + "|")
    print(" " * 35)
